---
title: "List of publications"
format: 
  html:
    code-fold: false
    code-tools: false
date: last-modified
---

# Preprints:

## 2026

Grattarola, F., Ortega-Solís, G., Soria, C. D., Tietje, M., **Wölke, F. J. R**., Fox, R., ... & Keil, P. (2026). Probabilistic species distributions from nine large-scale gridded atlases over five decades. *bioRxiv*, doi: <https://doi.org/10.64898/2026.09.24.754027>

*Haring, V., Midolo, G., Keil, P., Chytrý, M., Essl, F., Mendez, E.S., Padulosi, E., Borovyk, D., **Wölke, F**., Kalusová, V. and Preislerová, Z.*, (2026). *GRACE Resurvey of Central European Grassland Vegetation to study the Impacts of Country-Level Landscape Dynamics on Biodiversity.* EcoEvoRxiv. <https://doi.org/10.32942/X2R69X>

*Keil, P., **Wölke, F.**, Ortega-Solis, G., Grattarola, F., Leroy, F., Jansen, F., & Soria, C.* (2026). *Problems of geometry, sampling, and scale in gridded biodiversity data, and proposed solutions.* EcoEvoRxiv. <https://doi.org/10.32942/X29373>

*Ortega-Solís, G., Šťastný, K., Bejček, V., Telenský, T., Mellado Mansilla, D., Zárybnický, J., Grattarola, F., Zárybnická, M., Vermouzek, Z., Voříšek, P., Leroy, F., Tietje, M., Soria, C. D., Padulosi, E., Trávníčková, E., **Wölke, F**., & Keil, P.* (2026). *Opening a standardized, spatially contiguous biodiversity database collected over 40 years: Czech breeding bird atlases 1973—77, 1985—89, 2001—03, and 2014—17* \[Dataset\]. Czech University of Life Sciences. <https://doi.org/10.5281/zenodo.18503904>

*Gabriel R. Ortega-Solís, Karel Šťastný, Vladimír Bejček, Tomáš Telenský, Daniela Mellado-Mansilla, Jan Zárybnicky, Florencia Grattarola, Markéta Zárybnická, Zdeněk Vermouzek, Petr Voříšek, François Leroy, Melanie Tietje, Carmen Diana Soria, Elisa Padulosi, Eva Trávníčková, **Friederike Johanna Rosa Wölke**, Petr Keil.* (2026). *Opening a standardized, spatially contiguous biodiversity database collected over 40 years: Czech breeding bird atlases 1973—77, 1985—89, 2001—03, and 2014—17. bioRxiv 2026.05.29.728651; doi: <https://doi.org/10.64898/2026.05.29.728651>*

## 2025

***Friederike Wölke**, Gabriel Ortega Solís, Carmen Soria,* et al. *Predicting temporal change of species distributions from a single snapshot.* *Authorea*. 24 October 2024.\
DOI: <https://doi.org/10.22541/au.172978475.51624422/v1>

# Peer-reviewed:

## 2026

*Ferreira, R. S., Ringelberg, J. J., Hughes, C., Arlé, E., **Wölke, F. J.**, Tomlinson, K. W., & Onstein, R. E.* (2026). *The complex interaction between mammalian herbivores, climate, soil and fire has shaped the evolution and distribution of plant spinescence across biogeographical realms.* The New Phytologist, 251(6), 3640.[DOI: https://doi.org/10.1111/nph.71376](https://doi.org/10.1111/nph.71376)

*Soria, C. D., Ortega‐Solís, G. R., **Wölke, F. J.**, Barták, V., Leroy, F., Tschernosterová, K., ... & Keil, P.* (2026). *Spatial autocorrelation of species diversity and distributions in time and across spatial scales.* Global Ecology and Biogeography, 35(3), e70221.[DOI: https://doi.org/10.1111/geb.70221](https://doi.org/10.1111/geb.70221)

## 2023

***Wölke, F.J.R.**, Cabral, A., Lim, J.Y., Kissling, W.D. and Onstein, R.E.* (2023), *Africa as an evolutionary arena for large fruits*. New Phytol, 240: 1574-1586. [DOI: https://doi.org/10.1111/nph.19061](https://doi.org/10.1111/nph.19061)

# Other:

## 2023

Antonelli*, A., Fry*, C., Smith*, R.J., Eden*, J., Govaerts*, R.H.A., Kersey*, P., Nic Lughadha*, E., Onstein*, R.E., Simmonds*, M.S.J., Zizka*, A., Ackerman, J.D., Adams, V.M., Ainsworth, A.M., Albouy, C., Allen, A.P., Allen, S.P., Allio, R., Auld. T.D., Bachman, S.P., Baker, W.J., Barrett, R.L., Beaulieu, J.M., Bellot, S., Black, N., Boehnisch, G., Bogarín, D., Boyko, J.D., Brown, M.J.M., Budden, A., Bureš, P., Butt, N., Cabral, A., Cai, L., Cano, J.A., Chang, Y., Charitonidou, M., Chau, J.H., Cheek, M., Chomicki, G., Coiro, M., Colli-Silva, M., Condamine, F.L., Crayn, D.M., Cribb, P., Cuervo-Robayo, A.P., Dahlberg, A., Deklerck, V., Denelle, P., Dhanjal-Adams, K.L., Druzhinina, I., Eiserhardt, W.L., Elliott, T.L., Enquist, B.J., Escudero, M., Espinosa-Ruiz, S., Fay, M.F., Fernández, M., Flanagan, N.S., Forest, F., Fowler, R.M., Freiberg, M., Gallagher, R.V., Gaya, E., Gehrke, B., Gelwick, K., Grace, O.M., Granados Mendoza, C., Grenié, M., Groom, Q.J., Hackel, J., Hagen, E.R., Hágsater, E., Halley, J.M., Hu, A.-Q., Jaramillo, C., Kattge, J., Keith, D.A., Kirk, P., Kissling, W.D., Knapp, S., Kreft, H., Kuhnhäuser, B.G., Larridon, I., Leão, T.C.C., Leitch, I.J., Liimatainen, K., Lim, J.Y., Lucas, E., Lücking, R., Luján, M., Luo, A., Magallón, S., Maitner, B., Márquez-Corro, J.I., Martín-Bravo, S., Martins-Cunha, K., Mashau, A.C., Mauad, A.V., Maurin, O., Medina Lemos, R., Merow, C., Michelangeli, F.A., Mifsud, J.C.O., Mikryukov, V., Moat, J., Monro, A.K., Muasya, A.M., Mueller, G.M., Muellner-Riehl, A.N., Nargar, K., Negrão, R., Nicolson, N., Niskanen, T., Oliveira Andrino, C., Olmstead, R.G., Ondo, I., Oses, L., Parra-Sánchez, E., Paton, A.J., Pellicer, J., Pellissier, L., Pennington, T.D., Pérez-Escobar, O.A., Phillips, C., Pironon, S., Possingham, H., Prance, G., Przelomska, N.A.S., Ramírez-Barahona, S.A., Renner, S.S., Rincon, M., Rivers, M.C., Rojas Andrés, B.M., RomeroSoler, K.J., Roque, N., Rzedowski, J., Sanmartín, I., Santamaría-Aguilar, D., Schellenberger Costa, D., Serpell, E., Seyfullah, L.J., Shah, T., Shen, X., Silvestro, D., Simpson, D.A., Šmarda, P., Šmerda, J., Smidt, E., Smith, S.A., Solano-Gomez, R., Sothers, C., Soto Gomez, M., Spalink, D., Sperotto, P., Sun, M., Suz, L.M., Svenning, J.-C., Taylor, A., Tedersoo, L., Tietje, M., Trekels, M., Tremblay, R.L., Turner, R., Vasconcelos, T., Veselý, P., Villanueva, B.S., Villaverde, T., Vorontsova, M.S., Walker, B.E., Wang, Z., Watson, M., Weigelt, P., Wenk, E.H., Westrip, J.R.S., Wilkinson, T., Willett, S.D., Wilson, K.L., Winter, M., Wirth, C., **Wölke, F.J.R.**, Wright, I.J., Zedek, F., Zhigila, D.A., Zimmermann, N.E., Zuluaga, A., Zuntini, A.R. (2023). *State of the Worlds Plants and Fungi 2023*. **Royal Botanic Gardens, Kew.** [DOI: https://doi.org/10.34885/wnwn-6s63](https://doi.org/10.34885/wnwn-6s63)
